# Generated by Django 2.2.1 on 2022-07-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('AD', 'Admin'), ('ME', 'Employee')], default='ME', max_length=5),
        ),
    ]
