# Generated by Django 2.2.1 on 2022-07-22 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_clock'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
