# Generated by Django 3.0 on 2022-07-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_clock_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='clocked_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
